---
name: Developer image
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - "**.yml"
      - "**.go"
      - "Dockerfile"
      - "**.sh"
      - "go.mod"
      - "go.sum"

jobs:
  push:
    container: catthehacker/ubuntu:act-latest
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
          tags: type=raw,value=dev
          flavor: latest=false

      - name: Docker - Build / Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
